const express = require('express')
const router = express.Router()
const admin = require('./modules/admin')
const passport = require('../config/passport')
const { authenticated, authenticatedAdmin } = require('../middlewares/auth')
const bookController = require('../controllers/book-controller')
const userController = require('../controllers/user-controller')
router.use('/admin', authenticated, authenticatedAdmin, admin)
router.get('/signup', userController.signUpPage)
router.post('/signup', userController.signUp)
router.get('/signin', userController.signinPage)
router.post('/signin', passport.authenticate('local', { failureRedirect: '/signin', failureFlash: true }), userController.signin)
router.get('/logout', userController.logout)
router.get('/books', authenticated, bookController.getBooks)

router.use('/', (req, res) => res.redirect('/books'))
module.exports = router
